module.exports = {
    brands: [
        { title: 'Samsung', description: 'Global electronics leader' },
        { title: 'Apple', description: 'Premium tech and software' },
        {
            title: 'Sony',
            description: 'Audio, video and gaming specialist',
        },
        {
            title: 'LG',
            description: 'Home appliances and display innovator',
        },
        {
            title: 'Dell',
            description: 'Computer and enterprise solutions',
        },
        {
            title: 'Bosch',
            description: 'German precision tools and appliances',
        },
        { title: 'Nike', description: 'Performance sports apparel' },
        {
            title: 'Logitech',
            description: 'Computer peripherals and accessories',
        },
        { title: 'Xiaomi', description: 'Affordable smart technology' },
        {
            title: 'Asus',
            description: 'Gaming and high-performance hardware',
        },
        { title: 'HP', description: 'Printers and business laptops' },
        { title: 'Bose', description: 'High-end audio solutions' },
        {
            title: 'Nikon',
            description: 'Professional imaging equipment',
        },
        {
            title: 'Dyson',
            description: 'Innovative home cleaning technology',
        },
        {
            title: 'Philips',
            description: 'Lighting and personal healthcare',
        },
    ],
    customers: [
        {
            name: 'Alice Johnson',
            email: 'alice@test.com',
            password: 'password123',
        },
        {
            name: 'Bob Smith',
            email: 'bob@test.com',
            password: 'password123',
        },
        {
            name: 'Charlie Davis',
            email: 'charlie@test.com',
            password: 'password123',
        },
        {
            name: 'Michael Brown',
            email: 'michael@test.com',
            password: 'password123',
        },
        {
            name: 'Emily Wilson',
            email: 'emily@test.com',
            password: 'password123',
        },
        {
            name: 'David Miller',
            email: 'david@test.com',
            password: 'password123',
            password: 'password123',
        },
        {
            name: 'Sarah Taylor',
            email: 'sarah@test.com',
            password: 'password123',
        },
        {
            name: 'James Anderson',
            email: 'james@test.com',
            password: 'password123',
        },
        {
            name: 'Linda Thomas',
            email: 'linda@test.com',
            password: 'password123',
        },
        {
            name: 'Robert Moore',
            email: 'robert@test.com',
            password: 'password123',
        },
        {
            name: 'Jessica Lee',
            email: 'jessica@test.com',
            password: 'password123',
        },
        {
            name: 'William Garcia',
            email: 'will@test.com',
            password: 'password123',
        },
        {
            name: 'Karen White',
            email: 'karen@test.com',
            password: 'password123',
        },
        {
            name: 'Joseph Harris',
            email: 'joseph@test.com',
            password: 'password123',
        },
        {
            name: 'Nancy Martin',
            email: 'nancy@test.com',
            password: 'password123',
        },
    ],
    itemCategories: [
        {
            title: 'Smartphones',
            description: 'Mobile phones and handheld devices',
        },
        { title: 'Laptops', description: 'Portable personal computers' },
        {
            title: 'Home Appliances',
            description: 'Kitchen and laundry equipment',
        },
        {
            title: 'Audio',
            description: 'Headphones, speakers and hi-fi systems',
        },
        {
            title: 'TV & Video',
            description: 'Televisions and projectors',
        },
        {
            title: 'Wearables',
            description: 'Smartwatches and fitness trackers',
        },
        { title: 'Cameras', description: 'Photo and video equipment' },
        {
            title: 'Gaming',
            description: 'Consoles, controllers and PC gaming',
        },
        { title: 'Furniture', description: 'Home and office furniture' },
        {
            title: 'Sports',
            description: 'Gym equipment and outdoor gear',
        },
        {
            title: 'Kitchenware',
            description: 'Cooking tools and dining sets',
        },
        {
            title: 'Beauty',
            description: 'Personal care and grooming devices',
        },
        {
            title: 'Networking',
            description: 'Routers, switches and modems',
        },
        { title: 'Tools', description: 'Hand and power tools' },
        {
            title: 'Lighting',
            description: 'Smart bulbs and home lighting',
        },
    ],
    itemsOrders: [
        { item_id: 1, order_id: 1 },
        { item_id: 2, order_id: 2 },
        { item_id: 3, order_id: 3 },
        { item_id: 4, order_id: 4 },
        { item_id: 5, order_id: 5 },
        { item_id: 6, order_id: 6 },
        { item_id: 7, order_id: 7 },

        { item_id: 44, order_id: 8 },
        { item_id: 45, order_id: 8 },
        { item_id: 7, order_id: 8 },

        { item_id: 8, order_id: 9 },
        { item_id: 9, order_id: 10 },
        { item_id: 11, order_id: 11 },
        { item_id: 12, order_id: 12 },
        { item_id: 13, order_id: 13 },
        { item_id: 14, order_id: 14 },
        { item_id: 15, order_id: 15 },
        { item_id: 16, order_id: 16 },
        { item_id: 17, order_id: 17 },
        { item_id: 18, order_id: 18 },
        { item_id: 19, order_id: 19 },
        { item_id: 20, order_id: 20 },
        { item_id: 21, order_id: 21 },
        { item_id: 22, order_id: 22 },
        { item_id: 23, order_id: 23 },
        { item_id: 24, order_id: 24 },
        { item_id: 25, order_id: 25 },
        { item_id: 26, order_id: 26 },
        { item_id: 27, order_id: 27 },
        { item_id: 28, order_id: 28 },
        { item_id: 29, order_id: 29 },
        { item_id: 30, order_id: 30 },
        { item_id: 31, order_id: 31 },
        { item_id: 32, order_id: 32 },
        { item_id: 33, order_id: 33 },
        { item_id: 34, order_id: 34 },
        { item_id: 35, order_id: 35 },
        { item_id: 36, order_id: 36 },
        { item_id: 37, order_id: 37 },
        { item_id: 38, order_id: 38 },
        { item_id: 39, order_id: 39 },
        { item_id: 40, order_id: 40 },
        { item_id: 41, order_id: 41 },
        { item_id: 42, order_id: 42 },
        { item_id: 43, order_id: 43 },
        { item_id: 44, order_id: 44 },
        { item_id: 45, order_id: 45 },
        { item_id: 46, order_id: 46 },
        { item_id: 47, order_id: 47 },
        { item_id: 48, order_id: 48 },
        { item_id: 49, order_id: 49 },
        { item_id: 50, order_id: 50 },
    ],
    itemTypes: [
        {
            title: 'Mobile Phone',
            description: 'Cellular communication devices',
        },
        { title: 'Notebook', description: 'Portable workstation' },
        { title: 'Fridge', description: 'Food cooling and freezing' },
        {
            title: 'Wireless Earbuds',
            description: 'Bluetooth audio devices',
        },
        {
            title: 'OLED TV',
            description: 'High-end television displays',
        },
        { title: 'Smartwatch', description: 'Wrist-worn smart devices' },
        {
            title: 'DSLR Camera',
            description: 'Professional digital cameras',
        },
        {
            title: 'Game Console',
            description: 'Gaming hardware systems',
        },
        { title: 'Office Chair', description: 'Ergonomic seating' },
        { title: 'Treadmill', description: 'Indoor running equipment' },
        {
            title: 'Air Fryer',
            description: 'Healthy cooking appliances',
        },
        { title: 'Electric Shaver', description: 'Men grooming tools' },
        {
            title: 'Wi-Fi Router',
            description: 'Internet connectivity devices',
        },
        { title: 'Drill', description: 'Power tools for construction' },
        { title: 'Smart Bulb', description: 'IoT enabled lighting' },
    ],
    models: [
        { title: 'Galaxy S24', description: 'Flagship', brand_id: 1 },
        { title: 'Galaxy A54', description: 'Mid-range', brand_id: 1 },
        {
            title: 'Galaxy Watch 6',
            description: 'Wearable',
            brand_id: 1,
        },
        { title: 'QLED 4K TV', description: 'Display', brand_id: 1 },
        { title: 'Galaxy Tab S9', description: 'Tablet', brand_id: 1 },

        { title: 'iPhone 15', description: 'Flagship', brand_id: 2 },
        { title: 'MacBook Pro M3', description: 'Laptop', brand_id: 2 },
        { title: 'iPad Air', description: 'Tablet', brand_id: 2 },
        { title: 'AirPods Max', description: 'Audio', brand_id: 2 },
        {
            title: 'iPhone 15 Pro',
            description: 'Flagship',
            brand_id: 2,
        },

        { title: 'PlayStation 5', description: 'Gaming', brand_id: 3 },
        { title: 'WH-1000XM5', description: 'Headphones', brand_id: 3 },
        { title: 'Alpha 7 IV', description: 'Camera', brand_id: 3 },
        { title: 'Bravia XR', description: 'TV', brand_id: 3 },
        {
            title: 'PS5 Controller',
            description: 'Accessory',
            brand_id: 3,
        },

        { title: 'OLED C3', description: 'TV', brand_id: 4 },
        { title: 'InstaView', description: 'Fridge', brand_id: 4 },
        { title: 'Gram 17', description: 'Laptop', brand_id: 4 },
        { title: 'Air Fryer XXL', description: 'Kitchen', brand_id: 4 },

        { title: 'XPS 13', description: 'Laptop', brand_id: 5 },
        {
            title: 'Latitude 5000',
            description: 'Business PC',
            brand_id: 5,
        },
        { title: 'UltraSharp 27', description: 'Monitor', brand_id: 5 },
        { title: 'Dell G15', description: 'Gaming', brand_id: 5 },

        {
            title: 'Series 6',
            description: 'Washing Machine',
            brand_id: 6,
        },
        { title: 'Unlimited 7', description: 'Vacuum', brand_id: 6 },
        {
            title: 'EasyDrill 1200',
            description: 'Power tool',
            brand_id: 6,
        },

        { title: 'Air Max', description: 'Running', brand_id: 7 },
        { title: 'Pegasus 40', description: 'Training', brand_id: 7 },
        { title: 'Metcon 9', description: 'Gym', brand_id: 7 },

        { title: 'MX Master 3S', description: 'Mouse', brand_id: 8 },
        { title: 'G Pro X', description: 'Keyboard', brand_id: 8 },
        { title: 'C920', description: 'Webcam', brand_id: 8 },

        { title: 'Redmi Note 13', description: 'Phone', brand_id: 9 },
        { title: 'Mi Band 8', description: 'Tracker', brand_id: 9 },
        {
            title: 'Robot Vacuum S10',
            description: 'Cleaning',
            brand_id: 9,
        },

        {
            title: 'ROG Strix',
            description: 'Gaming Laptop',
            brand_id: 10,
        },
        {
            title: 'Zenbook S13',
            description: 'Ultrabook',
            brand_id: 10,
        },
        { title: 'RT-AX88U', description: 'Router', brand_id: 10 },

        { title: 'LaserJet Pro', description: 'Printer', brand_id: 11 },
        { title: 'Spectre x360', description: 'Laptop', brand_id: 11 },
        { title: 'Pavilion', description: 'Desktop', brand_id: 11 },

        {
            title: 'QuietComfort',
            description: 'Headphones',
            brand_id: 12,
        },
        { title: 'SoundLink', description: 'Speaker', brand_id: 12 },

        { title: 'Z9', description: 'Mirrorless Camera', brand_id: 13 },
        { title: 'D850', description: 'DSLR', brand_id: 13 },

        { title: 'V15 Detect', description: 'Vacuum', brand_id: 14 },
        { title: 'Airwrap', description: 'Beauty', brand_id: 14 },
        { title: 'Purifier Cool', description: 'Fan', brand_id: 14 },

        {
            title: 'Hue Starter Kit',
            description: 'Lighting',
            brand_id: 15,
        },
        { title: 'Sonicare', description: 'Health', brand_id: 15 },
        { title: 'OneBlade', description: 'Shaver', brand_id: 15 },
    ],
    items: [
        {
            category_id: 1,
            type_id: 1,
            brand_id: 1,
            model_id: 1,
            price: 1200.0,
            store_id: 1,
            amount: 10,
        },
        {
            category_id: 1,
            type_id: 1,
            brand_id: 1,
            model_id: 2,
            price: 450.0,
            store_id: 2,
            amount: 25,
        },
        {
            category_id: 1,
            type_id: 6,
            brand_id: 1,
            model_id: 3,
            price: 300.0,
            store_id: 1,
            amount: 15,
        },
        {
            category_id: 5,
            type_id: 5,
            brand_id: 1,
            model_id: 4,
            price: 900.0,
            store_id: 1,
            amount: 5,
        },
        {
            category_id: 1,
            type_id: 2,
            brand_id: 1,
            model_id: 5,
            price: 800.0,
            store_id: 2,
            amount: 8,
        },

        {
            category_id: 1,
            type_id: 1,
            brand_id: 2,
            model_id: 6,
            price: 1100.0,
            store_id: 1,
            amount: 12,
        },
        {
            category_id: 2,
            type_id: 2,
            brand_id: 2,
            model_id: 7,
            price: 2500.0,
            store_id: 1,
            amount: 7,
        },
        {
            category_id: 6,
            type_id: 6,
            brand_id: 2,
            model_id: 8,
            price: 400.0,
            store_id: 3,
            amount: 20,
        },
        {
            category_id: 4,
            type_id: 4,
            brand_id: 2,
            model_id: 9,
            price: 550.0,
            store_id: 5,
            amount: 30,
        },
        {
            category_id: 1,
            type_id: 1,
            brand_id: 2,
            model_id: 10,
            price: 1300.0,
            store_id: 1,
            amount: 10,
        },

        {
            category_id: 8,
            type_id: 8,
            brand_id: 3,
            model_id: 11,
            price: 500.0,
            store_id: 1,
            amount: 50,
        },
        {
            category_id: 4,
            type_id: 4,
            brand_id: 3,
            model_id: 12,
            price: 350.0,
            store_id: 5,
            amount: 40,
        },
        {
            category_id: 7,
            type_id: 7,
            brand_id: 3,
            model_id: 13,
            price: 2200.0,
            store_id: 1,
            amount: 5,
        },
        {
            category_id: 5,
            type_id: 5,
            brand_id: 3,
            model_id: 14,
            price: 1800.0,
            store_id: 3,
            amount: 3,
        },
        {
            category_id: 8,
            type_id: 8,
            brand_id: 3,
            model_id: 15,
            price: 70.0,
            store_id: 2,
            amount: 100,
        },

        {
            category_id: 5,
            type_id: 5,
            brand_id: 4,
            model_id: 16,
            price: 1300.0,
            store_id: 3,
            amount: 6,
        },
        {
            category_id: 3,
            type_id: 3,
            brand_id: 4,
            model_id: 17,
            price: 2200.0,
            store_id: 1,
            amount: 4,
        },
        {
            category_id: 2,
            type_id: 2,
            brand_id: 4,
            model_id: 18,
            price: 1400.0,
            store_id: 2,
            amount: 9,
        },
        {
            category_id: 3,
            type_id: 11,
            brand_id: 4,
            model_id: 19,
            price: 350.0,
            store_id: 5,
            amount: 15,
        },

        {
            category_id: 2,
            type_id: 2,
            brand_id: 5,
            model_id: 20,
            price: 1500.0,
            store_id: 2,
            amount: 11,
        },
        {
            category_id: 2,
            type_id: 2,
            brand_id: 5,
            model_id: 21,
            price: 1100.0,
            store_id: 2,
            amount: 14,
        },
        {
            category_id: 5,
            type_id: 3,
            brand_id: 5,
            model_id: 22,
            price: 450.0,
            store_id: 1,
            amount: 20,
        },
        {
            category_id: 8,
            type_id: 8,
            brand_id: 5,
            model_id: 23,
            price: 900.0,
            store_id: 4,
            amount: 6,
        },

        {
            category_id: 3,
            type_id: 3,
            brand_id: 6,
            model_id: 24,
            price: 700.0,
            store_id: 1,
            amount: 10,
        },
        {
            category_id: 3,
            type_id: 3,
            brand_id: 6,
            model_id: 25,
            price: 400.0,
            store_id: 3,
            amount: 12,
        },
        {
            category_id: 14,
            type_id: 14,
            brand_id: 6,
            model_id: 26,
            price: 150.0,
            store_id: 2,
            amount: 35,
        },

        {
            category_id: 10,
            type_id: 10,
            brand_id: 7,
            model_id: 27,
            price: 120.0,
            store_id: 4,
            amount: 60,
        },
        {
            category_id: 10,
            type_id: 10,
            brand_id: 7,
            model_id: 28,
            price: 110.0,
            store_id: 4,
            amount: 55,
        },
        {
            category_id: 10,
            type_id: 10,
            brand_id: 7,
            model_id: 29,
            price: 130.0,
            store_id: 4,
            amount: 40,
        },

        {
            category_id: 8,
            type_id: 8,
            brand_id: 8,
            model_id: 30,
            price: 100.0,
            store_id: 5,
            amount: 80,
        },
        {
            category_id: 8,
            type_id: 8,
            brand_id: 8,
            model_id: 31,
            price: 150.0,
            store_id: 2,
            amount: 25,
        },
        {
            category_id: 8,
            type_id: 13,
            brand_id: 8,
            model_id: 32,
            price: 80.0,
            store_id: 1,
            amount: 40,
        },

        {
            category_id: 1,
            type_id: 1,
            brand_id: 9,
            model_id: 33,
            price: 300.0,
            store_id: 5,
            amount: 70,
        },
        {
            category_id: 6,
            type_id: 6,
            brand_id: 9,
            model_id: 34,
            price: 50.0,
            store_id: 5,
            amount: 150,
        },
        {
            category_id: 3,
            type_id: 3,
            brand_id: 9,
            model_id: 35,
            price: 400.0,
            store_id: 3,
            amount: 10,
        },

        {
            category_id: 2,
            type_id: 2,
            brand_id: 10,
            model_id: 36,
            price: 1800.0,
            store_id: 2,
            amount: 5,
        },
        {
            category_id: 2,
            type_id: 2,
            brand_id: 10,
            model_id: 37,
            price: 1200.0,
            store_id: 4,
            amount: 8,
        },
        {
            category_id: 13,
            type_id: 13,
            brand_id: 10,
            model_id: 38,
            price: 200.0,
            store_id: 1,
            amount: 15,
        },

        {
            category_id: 11,
            type_id: 11,
            brand_id: 11,
            model_id: 39,
            price: 250.0,
            store_id: 1,
            amount: 20,
        },
        {
            category_id: 2,
            type_id: 2,
            brand_id: 11,
            model_id: 40,
            price: 1600.0,
            store_id: 2,
            amount: 4,
        },
        {
            category_id: 2,
            type_id: 2,
            brand_id: 11,
            model_id: 41,
            price: 800.0,
            store_id: 4,
            amount: 12,
        },

        {
            category_id: 4,
            type_id: 4,
            brand_id: 12,
            model_id: 42,
            price: 350.0,
            store_id: 4,
            amount: 45,
        },
        {
            category_id: 4,
            type_id: 4,
            brand_id: 12,
            model_id: 43,
            price: 200.0,
            store_id: 5,
            amount: 30,
        },

        {
            category_id: 7,
            type_id: 7,
            brand_id: 13,
            model_id: 44,
            price: 4500.0,
            store_id: 1,
            amount: 2,
        },
        {
            category_id: 7,
            type_id: 7,
            brand_id: 13,
            model_id: 45,
            price: 2800.0,
            store_id: 3,
            amount: 3,
        },

        {
            category_id: 3,
            type_id: 3,
            brand_id: 14,
            model_id: 46,
            price: 800.0,
            store_id: 2,
            amount: 10,
        },
        {
            category_id: 12,
            type_id: 12,
            brand_id: 14,
            model_id: 47,
            price: 500.0,
            store_id: 5,
            amount: 15,
        },
        {
            category_id: 5,
            type_id: 5,
            brand_id: 14,
            model_id: 48,
            price: 400.0,
            store_id: 1,
            amount: 7,
        },

        {
            category_id: 15,
            type_id: 15,
            brand_id: 15,
            model_id: 49,
            price: 100.0,
            store_id: 5,
            amount: 200,
        },
        {
            category_id: 12,
            type_id: 12,
            brand_id: 15,
            model_id: 50,
            price: 150.0,
            store_id: 1,
            amount: 40,
        },
    ],
    orders: [
        {
            code: 10001,
            date: '2026-03-10T13:12:58.402Z',
            amount: 1200.0,
            paid: false,
            customer_id: 1,
        },
        {
            code: 10002,
            date: '2026-03-10T13:12:58.402Z',
            amount: 450.0,
            paid: false,
            customer_id: 1,
        },
        {
            code: 10003,
            date: '2026-03-10T13:12:58.402Z',
            amount: 300.0,
            paid: false,
            customer_id: 1,
        },
        {
            code: 10004,
            date: '2026-03-10T13:12:58.402Z',
            amount: 150.0,
            paid: false,
            customer_id: 1,
        },
        {
            code: 10005,
            date: '2026-03-10T13:12:58.402Z',
            amount: 800.0,
            paid: false,
            customer_id: 1,
        },
        {
            code: 10006,
            date: '2026-03-10T13:12:58.402Z',
            amount: 100.0,
            paid: false,
            customer_id: 1,
        },
        {
            code: 10007,
            date: '2026-03-10T13:12:58.402Z',
            amount: 200.0,
            paid: false,
            customer_id: 1,
        },
        {
            code: 10008,
            date: '2026-03-10T13:12:58.402Z',
            amount: 9500.0,
            paid: false,
            customer_id: 4,
        },
        {
            code: 10009,
            date: '2026-03-10T13:12:58.402Z',
            amount: 1500.0,
            paid: false,
            customer_id: 2,
        },
        {
            code: 10010,
            date: '2026-03-10T13:12:58.402Z',
            amount: 600.0,
            paid: false,
            customer_id: 2,
        },
        {
            code: 10011,
            date: '2026-03-10T13:12:58.402Z',
            amount: 2200.0,
            paid: false,
            customer_id: 3,
        },
        {
            code: 10012,
            date: '2026-03-10T13:12:58.402Z',
            amount: 500.0,
            paid: false,
            customer_id: 5,
        },
        {
            code: 10013,
            date: '2026-03-10T13:12:58.402Z',
            amount: 150.0,
            paid: false,
            customer_id: 6,
        },
        {
            code: 10014,
            date: '2026-03-10T13:12:58.402Z',
            amount: 80.0,
            paid: false,
            customer_id: 7,
        },
        {
            code: 10015,
            date: '2026-03-10T13:12:58.402Z',
            amount: 120.0,
            paid: false,
            customer_id: 8,
        },
        {
            code: 10016,
            date: '2026-03-10T13:12:58.402Z',
            amount: 250.0,
            paid: false,
            customer_id: 9,
        },
        {
            code: 10017,
            date: '2026-03-10T13:12:58.402Z',
            amount: 400.0,
            paid: false,
            customer_id: 10,
        },
        {
            code: 10018,
            date: '2026-03-10T13:12:58.402Z',
            amount: 900.0,
            paid: false,
            customer_id: 11,
        },
        {
            code: 10019,
            date: '2026-03-10T13:12:58.402Z',
            amount: 110.0,
            paid: false,
            customer_id: 12,
        },
        {
            code: 10020,
            date: '2026-03-10T13:12:58.402Z',
            amount: 300.0,
            paid: false,
            customer_id: 13,
        },
        {
            code: 10021,
            date: '2026-03-10T13:12:58.402Z',
            amount: 450.0,
            paid: false,
            customer_id: 14,
        },
        {
            code: 10022,
            date: '2026-03-10T13:12:58.402Z',
            amount: 600.0,
            paid: false,
            customer_id: 15,
        },
        {
            code: 10023,
            date: '2026-03-10T13:12:58.402Z',
            amount: 700.0,
            paid: false,
            customer_id: 2,
        },
        {
            code: 10024,
            date: '2026-03-10T13:12:58.402Z',
            amount: 100.0,
            paid: false,
            customer_id: 3,
        },
        {
            code: 10025,
            date: '2026-03-10T13:12:58.402Z',
            amount: 200.0,
            paid: false,
            customer_id: 5,
        },
        {
            code: 10026,
            date: '2026-03-10T13:12:58.402Z',
            amount: 300.0,
            paid: false,
            customer_id: 6,
        },
        {
            code: 10027,
            date: '2026-03-10T13:12:58.402Z',
            amount: 400.0,
            paid: false,
            customer_id: 7,
        },
        {
            code: 10028,
            date: '2026-03-10T13:12:58.402Z',
            amount: 500.0,
            paid: false,
            customer_id: 8,
        },
        {
            code: 10029,
            date: '2026-03-10T13:12:58.402Z',
            amount: 600.0,
            paid: false,
            customer_id: 9,
        },
        {
            code: 10030,
            date: '2026-03-10T13:12:58.402Z',
            amount: 700.0,
            paid: false,
            customer_id: 10,
        },

        {
            code: 10031,
            date: '2026-03-10T13:12:58.402Z',
            amount: 800.0,
            paid: false,
            customer_id: 11,
        },
        {
            code: 10032,
            date: '2026-03-10T13:12:58.402Z',
            amount: 900.0,
            paid: false,
            customer_id: 12,
        },
        {
            code: 10033,
            date: '2026-03-10T13:12:58.402Z',
            amount: 1000.0,
            paid: false,
            customer_id: 13,
        },
        {
            code: 10034,
            date: '2026-03-10T13:12:58.402Z',
            amount: 110.0,
            paid: false,
            customer_id: 14,
        },
        {
            code: 10035,
            date: '2026-03-10T13:12:58.402Z',
            amount: 220.0,
            paid: false,
            customer_id: 15,
        },
        {
            code: 10036,
            date: '2026-03-10T13:12:58.402Z',
            amount: 330.0,
            paid: false,
            customer_id: 2,
        },
        {
            code: 10037,
            date: '2026-03-10T13:12:58.402Z',
            amount: 440.0,
            paid: false,
            customer_id: 3,
        },
        {
            code: 10038,
            date: '2026-03-10T13:12:58.402Z',
            amount: 550.0,
            paid: false,
            customer_id: 5,
        },
        {
            code: 10039,
            date: '2026-03-10T13:12:58.402Z',
            amount: 660.0,
            paid: false,
            customer_id: 6,
        },
        {
            code: 10040,
            date: '2026-03-10T13:12:58.402Z',
            amount: 770.0,
            paid: false,
            customer_id: 7,
        },

        {
            code: 10041,
            date: '2026-03-10T13:12:58.402Z',
            amount: 880.0,
            paid: false,
            customer_id: 8,
        },
        {
            code: 10042,
            date: '2026-03-10T13:12:58.402Z',
            amount: 990.0,
            paid: false,
            customer_id: 9,
        },
        {
            code: 10043,
            date: '2026-03-10T13:12:58.402Z',
            amount: 150.0,
            paid: false,
            customer_id: 10,
        },
        {
            code: 10044,
            date: '2026-03-10T13:12:58.402Z',
            amount: 250.0,
            paid: false,
            customer_id: 11,
        },
        {
            code: 10045,
            date: '2026-03-10T13:12:58.402Z',
            amount: 350.0,
            paid: false,
            customer_id: 12,
        },
        {
            code: 10046,
            date: '2026-03-10T13:12:58.402Z',
            amount: 450.0,
            paid: false,
            customer_id: 13,
        },
        {
            code: 10047,
            date: '2026-03-10T13:12:58.402Z',
            amount: 550.0,
            paid: false,
            customer_id: 14,
        },
        {
            code: 10048,
            date: '2026-03-10T13:12:58.402Z',
            amount: 650.0,
            paid: false,
            customer_id: 15,
        },
        {
            code: 10049,
            date: '2026-03-10T13:12:58.402Z',
            amount: 750.0,
            paid: false,
            customer_id: 2,
        },
        {
            code: 10050,
            date: '2026-03-10T13:12:58.402Z',
            amount: 850.0,
            paid: false,
            customer_id: 3,
        },
    ],
    stores: [
        {
            title: 'Main Warehouse',
            description: 'Central distribution hub in Kyiv',
        },
        {
            title: 'Western Hub',
            description: 'Regional warehouse in Lviv',
        },
        {
            title: 'Southern Port',
            description: 'Import terminal in Odesa',
        },
        {
            title: 'Eastern Branch',
            description: 'Warehouse facility in Kharkiv',
        },
        {
            title: 'Retail Outlet',
            description: 'Direct store warehouse in Dnipro',
        },
    ],
};
