module.exports = {
    brands: [
        { id: 1, title: 'Samsung', description: 'Global electronics leader' },
        { id: 2, title: 'Apple', description: 'Premium tech and software' },
        {
            id: 3,
            title: 'Sony',
            description: 'Audio, video and gaming specialist',
        },
        {
            id: 4,
            title: 'LG',
            description: 'Home appliances and display innovator',
        },
        {
            id: 5,
            title: 'Dell',
            description: 'Computer and enterprise solutions',
        },
        {
            id: 6,
            title: 'Bosch',
            description: 'German precision tools and appliances',
        },
        { id: 7, title: 'Nike', description: 'Performance sports apparel' },
        {
            id: 8,
            title: 'Logitech',
            description: 'Computer peripherals and accessories',
        },
        { id: 9, title: 'Xiaomi', description: 'Affordable smart technology' },
        {
            id: 10,
            title: 'Asus',
            description: 'Gaming and high-performance hardware',
        },
        { id: 11, title: 'HP', description: 'Printers and business laptops' },
        { id: 12, title: 'Bose', description: 'High-end audio solutions' },
        {
            id: 13,
            title: 'Nikon',
            description: 'Professional imaging equipment',
        },
        {
            id: 14,
            title: 'Dyson',
            description: 'Innovative home cleaning technology',
        },
        {
            id: 15,
            title: 'Philips',
            description: 'Lighting and personal healthcare',
        },
    ],
    customers: [
        { id: 1, name: 'Alice Johnson', email: 'alice@test.com' },
        { id: 2, name: 'Bob Smith', email: 'bob@test.com' },
        { id: 3, name: 'Charlie Davis', email: 'charlie@test.com' },
        { id: 4, name: 'Michael Brown', email: 'michael@test.com' },
        { id: 5, name: 'Emily Wilson', email: 'emily@test.com' },
        { id: 6, name: 'David Miller', email: 'david@test.com' },
        { id: 7, name: 'Sarah Taylor', email: 'sarah@test.com' },
        { id: 8, name: 'James Anderson', email: 'james@test.com' },
        { id: 9, name: 'Linda Thomas', email: 'linda@test.com' },
        { id: 10, name: 'Robert Moore', email: 'robert@test.com' },
        { id: 11, name: 'Jessica Lee', email: 'jessica@test.com' },
        { id: 12, name: 'William Garcia', email: 'will@test.com' },
        { id: 13, name: 'Karen White', email: 'karen@test.com' },
        { id: 14, name: 'Joseph Harris', email: 'joseph@test.com' },
        { id: 15, name: 'Nancy Martin', email: 'nancy@test.com' },
    ],
    itemCategories: [
        {
            id: 1,
            title: 'Smartphones',
            description: 'Mobile phones and handheld devices',
        },
        { id: 2, title: 'Laptops', description: 'Portable personal computers' },
        {
            id: 3,
            title: 'Home Appliances',
            description: 'Kitchen and laundry equipment',
        },
        {
            id: 4,
            title: 'Audio',
            description: 'Headphones, speakers and hi-fi systems',
        },
        {
            id: 5,
            title: 'TV & Video',
            description: 'Televisions and projectors',
        },
        {
            id: 6,
            title: 'Wearables',
            description: 'Smartwatches and fitness trackers',
        },
        { id: 7, title: 'Cameras', description: 'Photo and video equipment' },
        {
            id: 8,
            title: 'Gaming',
            description: 'Consoles, controllers and PC gaming',
        },
        { id: 9, title: 'Furniture', description: 'Home and office furniture' },
        {
            id: 10,
            title: 'Sports',
            description: 'Gym equipment and outdoor gear',
        },
        {
            id: 11,
            title: 'Kitchenware',
            description: 'Cooking tools and dining sets',
        },
        {
            id: 12,
            title: 'Beauty',
            description: 'Personal care and grooming devices',
        },
        {
            id: 13,
            title: 'Networking',
            description: 'Routers, switches and modems',
        },
        { id: 14, title: 'Tools', description: 'Hand and power tools' },
        {
            id: 15,
            title: 'Lighting',
            description: 'Smart bulbs and home lighting',
        },
    ],
    itemOrder: [
        { item_id: 1, order_id: 1 },
        { item_id: 2, order_id: 2 },
        { item_id: 3, order_id: 3 },
        { item_id: 4, order_id: 4 },
        { item_id: 5, order_id: 5 },
        { item_id: 6, order_id: 6 },
        { item_id: 7, order_id: 7 },

        { item_id: 44, order_id: 8 },
        { item_id: 45, order_id: 8 },
        { item_id: 7, order_id: 8 },

        { item_id: 8, order_id: 9 },
        { item_id: 9, order_id: 10 },
        { item_id: 11, order_id: 11 },
        { item_id: 12, order_id: 12 },
        { item_id: 13, order_id: 13 },
        { item_id: 14, order_id: 14 },
        { item_id: 15, order_id: 15 },
        { item_id: 16, order_id: 16 },
        { item_id: 17, order_id: 17 },
        { item_id: 18, order_id: 18 },
        { item_id: 19, order_id: 19 },
        { item_id: 20, order_id: 20 },
        { item_id: 21, order_id: 21 },
        { item_id: 22, order_id: 22 },
        { item_id: 23, order_id: 23 },
        { item_id: 24, order_id: 24 },
        { item_id: 25, order_id: 25 },
        { item_id: 26, order_id: 26 },
        { item_id: 27, order_id: 27 },
        { item_id: 28, order_id: 28 },
        { item_id: 29, order_id: 29 },
        { item_id: 30, order_id: 30 },
        { item_id: 31, order_id: 31 },
        { item_id: 32, order_id: 32 },
        { item_id: 33, order_id: 33 },
        { item_id: 34, order_id: 34 },
        { item_id: 35, order_id: 35 },
        { item_id: 36, order_id: 36 },
        { item_id: 37, order_id: 37 },
        { item_id: 38, order_id: 38 },
        { item_id: 39, order_id: 39 },
        { item_id: 40, order_id: 40 },
        { item_id: 41, order_id: 41 },
        { item_id: 42, order_id: 42 },
        { item_id: 43, order_id: 43 },
        { item_id: 44, order_id: 44 },
        { item_id: 45, order_id: 45 },
        { item_id: 46, order_id: 46 },
        { item_id: 47, order_id: 47 },
        { item_id: 48, order_id: 48 },
        { item_id: 49, order_id: 49 },
        { item_id: 50, order_id: 50 },
    ],
    itemTypes: [
        {
            id: 1,
            title: 'Mobile Phone',
            description: 'Cellular communication devices',
        },
        { id: 2, title: 'Notebook', description: 'Portable workstation' },
        { id: 3, title: 'Fridge', description: 'Food cooling and freezing' },
        {
            id: 4,
            title: 'Wireless Earbuds',
            description: 'Bluetooth audio devices',
        },
        {
            id: 5,
            title: 'OLED TV',
            description: 'High-end television displays',
        },
        { id: 6, title: 'Smartwatch', description: 'Wrist-worn smart devices' },
        {
            id: 7,
            title: 'DSLR Camera',
            description: 'Professional digital cameras',
        },
        {
            id: 8,
            title: 'Game Console',
            description: 'Gaming hardware systems',
        },
        { id: 9, title: 'Office Chair', description: 'Ergonomic seating' },
        { id: 10, title: 'Treadmill', description: 'Indoor running equipment' },
        {
            id: 11,
            title: 'Air Fryer',
            description: 'Healthy cooking appliances',
        },
        { id: 12, title: 'Electric Shaver', description: 'Men grooming tools' },
        {
            id: 13,
            title: 'Wi-Fi Router',
            description: 'Internet connectivity devices',
        },
        { id: 14, title: 'Drill', description: 'Power tools for construction' },
        { id: 15, title: 'Smart Bulb', description: 'IoT enabled lighting' },
    ],
    models: [
        { id: 1, title: 'Galaxy S24', description: 'Flagship', brand_id: 1 },
        { id: 2, title: 'Galaxy A54', description: 'Mid-range', brand_id: 1 },
        {
            id: 3,
            title: 'Galaxy Watch 6',
            description: 'Wearable',
            brand_id: 1,
        },
        { id: 4, title: 'QLED 4K TV', description: 'Display', brand_id: 1 },
        { id: 5, title: 'Galaxy Tab S9', description: 'Tablet', brand_id: 1 },

        { id: 6, title: 'iPhone 15', description: 'Flagship', brand_id: 2 },
        { id: 7, title: 'MacBook Pro M3', description: 'Laptop', brand_id: 2 },
        { id: 8, title: 'iPad Air', description: 'Tablet', brand_id: 2 },
        { id: 9, title: 'AirPods Max', description: 'Audio', brand_id: 2 },
        {
            id: 10,
            title: 'iPhone 15 Pro',
            description: 'Flagship',
            brand_id: 2,
        },

        { id: 11, title: 'PlayStation 5', description: 'Gaming', brand_id: 3 },
        { id: 12, title: 'WH-1000XM5', description: 'Headphones', brand_id: 3 },
        { id: 13, title: 'Alpha 7 IV', description: 'Camera', brand_id: 3 },
        { id: 14, title: 'Bravia XR', description: 'TV', brand_id: 3 },
        {
            id: 15,
            title: 'PS5 Controller',
            description: 'Accessory',
            brand_id: 3,
        },

        { id: 16, title: 'OLED C3', description: 'TV', brand_id: 4 },
        { id: 17, title: 'InstaView', description: 'Fridge', brand_id: 4 },
        { id: 18, title: 'Gram 17', description: 'Laptop', brand_id: 4 },
        { id: 19, title: 'Air Fryer XXL', description: 'Kitchen', brand_id: 4 },

        { id: 20, title: 'XPS 13', description: 'Laptop', brand_id: 5 },
        {
            id: 21,
            title: 'Latitude 5000',
            description: 'Business PC',
            brand_id: 5,
        },
        { id: 22, title: 'UltraSharp 27', description: 'Monitor', brand_id: 5 },
        { id: 23, title: 'Dell G15', description: 'Gaming', brand_id: 5 },

        {
            id: 24,
            title: 'Series 6',
            description: 'Washing Machine',
            brand_id: 6,
        },
        { id: 25, title: 'Unlimited 7', description: 'Vacuum', brand_id: 6 },
        {
            id: 26,
            title: 'EasyDrill 1200',
            description: 'Power tool',
            brand_id: 6,
        },

        { id: 27, title: 'Air Max', description: 'Running', brand_id: 7 },
        { id: 28, title: 'Pegasus 40', description: 'Training', brand_id: 7 },
        { id: 29, title: 'Metcon 9', description: 'Gym', brand_id: 7 },

        { id: 30, title: 'MX Master 3S', description: 'Mouse', brand_id: 8 },
        { id: 31, title: 'G Pro X', description: 'Keyboard', brand_id: 8 },
        { id: 32, title: 'C920', description: 'Webcam', brand_id: 8 },

        { id: 33, title: 'Redmi Note 13', description: 'Phone', brand_id: 9 },
        { id: 34, title: 'Mi Band 8', description: 'Tracker', brand_id: 9 },
        {
            id: 35,
            title: 'Robot Vacuum S10',
            description: 'Cleaning',
            brand_id: 9,
        },

        {
            id: 36,
            title: 'ROG Strix',
            description: 'Gaming Laptop',
            brand_id: 10,
        },
        {
            id: 37,
            title: 'Zenbook S13',
            description: 'Ultrabook',
            brand_id: 10,
        },
        { id: 38, title: 'RT-AX88U', description: 'Router', brand_id: 10 },

        { id: 39, title: 'LaserJet Pro', description: 'Printer', brand_id: 11 },
        { id: 40, title: 'Spectre x360', description: 'Laptop', brand_id: 11 },
        { id: 41, title: 'Pavilion', description: 'Desktop', brand_id: 11 },

        {
            id: 42,
            title: 'QuietComfort',
            description: 'Headphones',
            brand_id: 12,
        },
        { id: 43, title: 'SoundLink', description: 'Speaker', brand_id: 12 },

        { id: 44, title: 'Z9', description: 'Mirrorless Camera', brand_id: 13 },
        { id: 45, title: 'D850', description: 'DSLR', brand_id: 13 },

        { id: 46, title: 'V15 Detect', description: 'Vacuum', brand_id: 14 },
        { id: 47, title: 'Airwrap', description: 'Beauty', brand_id: 14 },
        { id: 48, title: 'Purifier Cool', description: 'Fan', brand_id: 14 },

        {
            id: 49,
            title: 'Hue Starter Kit',
            description: 'Lighting',
            brand_id: 15,
        },
        { id: 50, title: 'Sonicare', description: 'Health', brand_id: 15 },
        { id: 51, title: 'OneBlade', description: 'Shaver', brand_id: 15 },
    ],
    items: [
        {
            id: 1,
            category_id: 1,
            type_id: 1,
            brand_id: 1,
            model_id: 1,
            price: 1200.0,
            store_id: 1,
            amount: 10,
        },
        {
            id: 2,
            category_id: 1,
            type_id: 1,
            brand_id: 1,
            model_id: 2,
            price: 450.0,
            store_id: 2,
            amount: 25,
        },
        {
            id: 3,
            category_id: 1,
            type_id: 6,
            brand_id: 1,
            model_id: 3,
            price: 300.0,
            store_id: 1,
            amount: 15,
        },
        {
            id: 4,
            category_id: 5,
            type_id: 5,
            brand_id: 1,
            model_id: 4,
            price: 900.0,
            store_id: 1,
            amount: 5,
        },
        {
            id: 5,
            category_id: 1,
            type_id: 2,
            brand_id: 1,
            model_id: 5,
            price: 800.0,
            store_id: 2,
            amount: 8,
        },

        {
            id: 6,
            category_id: 1,
            type_id: 1,
            brand_id: 2,
            model_id: 6,
            price: 1100.0,
            store_id: 1,
            amount: 12,
        },
        {
            id: 7,
            category_id: 2,
            type_id: 2,
            brand_id: 2,
            model_id: 7,
            price: 2500.0,
            store_id: 1,
            amount: 7,
        },
        {
            id: 8,
            category_id: 6,
            type_id: 6,
            brand_id: 2,
            model_id: 8,
            price: 400.0,
            store_id: 3,
            amount: 20,
        },
        {
            id: 9,
            category_id: 4,
            type_id: 4,
            brand_id: 2,
            model_id: 9,
            price: 550.0,
            store_id: 5,
            amount: 30,
        },
        {
            id: 10,
            category_id: 1,
            type_id: 1,
            brand_id: 2,
            model_id: 10,
            price: 1300.0,
            store_id: 1,
            amount: 10,
        },

        {
            id: 11,
            category_id: 8,
            type_id: 8,
            brand_id: 3,
            model_id: 11,
            price: 500.0,
            store_id: 1,
            amount: 50,
        },
        {
            id: 12,
            category_id: 4,
            type_id: 4,
            brand_id: 3,
            model_id: 12,
            price: 350.0,
            store_id: 5,
            amount: 40,
        },
        {
            id: 13,
            category_id: 7,
            type_id: 7,
            brand_id: 3,
            model_id: 13,
            price: 2200.0,
            store_id: 1,
            amount: 5,
        },
        {
            id: 14,
            category_id: 5,
            type_id: 5,
            brand_id: 3,
            model_id: 14,
            price: 1800.0,
            store_id: 3,
            amount: 3,
        },
        {
            id: 15,
            category_id: 8,
            type_id: 8,
            brand_id: 3,
            model_id: 15,
            price: 70.0,
            store_id: 2,
            amount: 100,
        },

        {
            id: 16,
            category_id: 5,
            type_id: 5,
            brand_id: 4,
            model_id: 16,
            price: 1300.0,
            store_id: 3,
            amount: 6,
        },
        {
            id: 17,
            category_id: 3,
            type_id: 3,
            brand_id: 4,
            model_id: 17,
            price: 2200.0,
            store_id: 1,
            amount: 4,
        },
        {
            id: 18,
            category_id: 2,
            type_id: 2,
            brand_id: 4,
            model_id: 18,
            price: 1400.0,
            store_id: 2,
            amount: 9,
        },
        {
            id: 19,
            category_id: 3,
            type_id: 11,
            brand_id: 4,
            model_id: 19,
            price: 350.0,
            store_id: 5,
            amount: 15,
        },

        {
            id: 20,
            category_id: 2,
            type_id: 2,
            brand_id: 5,
            model_id: 20,
            price: 1500.0,
            store_id: 2,
            amount: 11,
        },
        {
            id: 21,
            category_id: 2,
            type_id: 2,
            brand_id: 5,
            model_id: 21,
            price: 1100.0,
            store_id: 2,
            amount: 14,
        },
        {
            id: 22,
            category_id: 5,
            type_id: 3,
            brand_id: 5,
            model_id: 22,
            price: 450.0,
            store_id: 1,
            amount: 20,
        },
        {
            id: 23,
            category_id: 8,
            type_id: 8,
            brand_id: 5,
            model_id: 23,
            price: 900.0,
            store_id: 4,
            amount: 6,
        },

        {
            id: 24,
            category_id: 3,
            type_id: 3,
            brand_id: 6,
            model_id: 24,
            price: 700.0,
            store_id: 1,
            amount: 10,
        },
        {
            id: 25,
            category_id: 3,
            type_id: 3,
            brand_id: 6,
            model_id: 25,
            price: 400.0,
            store_id: 3,
            amount: 12,
        },
        {
            id: 26,
            category_id: 14,
            type_id: 14,
            brand_id: 6,
            model_id: 26,
            price: 150.0,
            store_id: 2,
            amount: 35,
        },

        {
            id: 27,
            category_id: 10,
            type_id: 10,
            brand_id: 7,
            model_id: 27,
            price: 120.0,
            store_id: 4,
            amount: 60,
        },
        {
            id: 28,
            category_id: 10,
            type_id: 10,
            brand_id: 7,
            model_id: 28,
            price: 110.0,
            store_id: 4,
            amount: 55,
        },
        {
            id: 29,
            category_id: 10,
            type_id: 10,
            brand_id: 7,
            model_id: 29,
            price: 130.0,
            store_id: 4,
            amount: 40,
        },

        {
            id: 30,
            category_id: 8,
            type_id: 8,
            brand_id: 8,
            model_id: 30,
            price: 100.0,
            store_id: 5,
            amount: 80,
        },
        {
            id: 31,
            category_id: 8,
            type_id: 8,
            brand_id: 8,
            model_id: 31,
            price: 150.0,
            store_id: 2,
            amount: 25,
        },
        {
            id: 32,
            category_id: 8,
            type_id: 13,
            brand_id: 8,
            model_id: 32,
            price: 80.0,
            store_id: 1,
            amount: 40,
        },

        {
            id: 33,
            category_id: 1,
            type_id: 1,
            brand_id: 9,
            model_id: 33,
            price: 300.0,
            store_id: 5,
            amount: 70,
        },
        {
            id: 34,
            category_id: 6,
            type_id: 6,
            brand_id: 9,
            model_id: 34,
            price: 50.0,
            store_id: 5,
            amount: 150,
        },
        {
            id: 35,
            category_id: 3,
            type_id: 3,
            brand_id: 9,
            model_id: 35,
            price: 400.0,
            store_id: 3,
            amount: 10,
        },

        {
            id: 36,
            category_id: 2,
            type_id: 2,
            brand_id: 10,
            model_id: 36,
            price: 1800.0,
            store_id: 2,
            amount: 5,
        },
        {
            id: 37,
            category_id: 2,
            type_id: 2,
            brand_id: 10,
            model_id: 37,
            price: 1200.0,
            store_id: 4,
            amount: 8,
        },
        {
            id: 38,
            category_id: 13,
            type_id: 13,
            brand_id: 10,
            model_id: 38,
            price: 200.0,
            store_id: 1,
            amount: 15,
        },

        {
            id: 39,
            category_id: 11,
            type_id: 11,
            brand_id: 11,
            model_id: 39,
            price: 250.0,
            store_id: 1,
            amount: 20,
        },
        {
            id: 40,
            category_id: 2,
            type_id: 2,
            brand_id: 11,
            model_id: 40,
            price: 1600.0,
            store_id: 2,
            amount: 4,
        },
        {
            id: 41,
            category_id: 2,
            type_id: 2,
            brand_id: 11,
            model_id: 41,
            price: 800.0,
            store_id: 4,
            amount: 12,
        },

        {
            id: 42,
            category_id: 4,
            type_id: 4,
            brand_id: 12,
            model_id: 42,
            price: 350.0,
            store_id: 4,
            amount: 45,
        },
        {
            id: 43,
            category_id: 4,
            type_id: 4,
            brand_id: 12,
            model_id: 43,
            price: 200.0,
            store_id: 5,
            amount: 30,
        },

        {
            id: 44,
            category_id: 7,
            type_id: 7,
            brand_id: 13,
            model_id: 44,
            price: 4500.0,
            store_id: 1,
            amount: 2,
        },
        {
            id: 45,
            category_id: 7,
            type_id: 7,
            brand_id: 13,
            model_id: 45,
            price: 2800.0,
            store_id: 3,
            amount: 3,
        },

        {
            id: 46,
            category_id: 3,
            type_id: 3,
            brand_id: 14,
            model_id: 46,
            price: 800.0,
            store_id: 2,
            amount: 10,
        },
        {
            id: 47,
            category_id: 12,
            type_id: 12,
            brand_id: 14,
            model_id: 47,
            price: 500.0,
            store_id: 5,
            amount: 15,
        },
        {
            id: 48,
            category_id: 5,
            type_id: 5,
            brand_id: 14,
            model_id: 48,
            price: 400.0,
            store_id: 1,
            amount: 7,
        },

        {
            id: 49,
            category_id: 15,
            type_id: 15,
            brand_id: 15,
            model_id: 49,
            price: 100.0,
            store_id: 5,
            amount: 200,
        },
        {
            id: 50,
            category_id: 12,
            type_id: 12,
            brand_id: 15,
            model_id: 50,
            price: 150.0,
            store_id: 1,
            amount: 40,
        },
    ],
    orders: [
        {
            id: 1,
            code: 'ORD-001',
            date: '2026-03-10T13:12:58.402Z',
            amount: 1200.0,
            paid: false,
            customer_id: 1,
        },
        {
            id: 2,
            code: 'ORD-002',
            date: '2026-03-10T13:12:58.402Z',
            amount: 450.0,
            paid: false,
            customer_id: 1,
        },
        {
            id: 3,
            code: 'ORD-003',
            date: '2026-03-10T13:12:58.402Z',
            amount: 300.0,
            paid: false,
            customer_id: 1,
        },
        {
            id: 4,
            code: 'ORD-004',
            date: '2026-03-10T13:12:58.402Z',
            amount: 150.0,
            paid: false,
            customer_id: 1,
        },
        {
            id: 5,
            code: 'ORD-005',
            date: '2026-03-10T13:12:58.402Z',
            amount: 800.0,
            paid: false,
            customer_id: 1,
        },
        {
            id: 6,
            code: 'ORD-006',
            date: '2026-03-10T13:12:58.402Z',
            amount: 100.0,
            paid: false,
            customer_id: 1,
        },
        {
            id: 7,
            code: 'ORD-007',
            date: '2026-03-10T13:12:58.402Z',
            amount: 200.0,
            paid: false,
            customer_id: 1,
        },
        {
            id: 8,
            code: 'ORD-008',
            date: '2026-03-10T13:12:58.402Z',
            amount: 9500.0,
            paid: false,
            customer_id: 4,
        },
        {
            id: 9,
            code: 'ORD-009',
            date: '2026-03-10T13:12:58.402Z',
            amount: 1500.0,
            paid: false,
            customer_id: 2,
        },
        {
            id: 10,
            code: 'ORD-010',
            date: '2026-03-10T13:12:58.402Z',
            amount: 600.0,
            paid: false,
            customer_id: 2,
        },
        {
            id: 11,
            code: 'ORD-011',
            date: '2026-03-10T13:12:58.402Z',
            amount: 2200.0,
            paid: false,
            customer_id: 3,
        },
        {
            id: 12,
            code: 'ORD-012',
            date: '2026-03-10T13:12:58.402Z',
            amount: 500.0,
            paid: false,
            customer_id: 5,
        },
        {
            id: 13,
            code: 'ORD-013',
            date: '2026-03-10T13:12:58.402Z',
            amount: 150.0,
            paid: false,
            customer_id: 6,
        },
        {
            id: 14,
            code: 'ORD-014',
            date: '2026-03-10T13:12:58.402Z',
            amount: 80.0,
            paid: false,
            customer_id: 7,
        },
        {
            id: 15,
            code: 'ORD-015',
            date: '2026-03-10T13:12:58.402Z',
            amount: 120.0,
            paid: false,
            customer_id: 8,
        },
        {
            id: 16,
            code: 'ORD-016',
            date: '2026-03-10T13:12:58.402Z',
            amount: 250.0,
            paid: false,
            customer_id: 9,
        },
        {
            id: 17,
            code: 'ORD-017',
            date: '2026-03-10T13:12:58.402Z',
            amount: 400.0,
            paid: false,
            customer_id: 10,
        },
        {
            id: 18,
            code: 'ORD-018',
            date: '2026-03-10T13:12:58.402Z',
            amount: 900.0,
            paid: false,
            customer_id: 11,
        },
        {
            id: 19,
            code: 'ORD-019',
            date: '2026-03-10T13:12:58.402Z',
            amount: 110.0,
            paid: false,
            customer_id: 12,
        },
        {
            id: 20,
            code: 'ORD-020',
            date: '2026-03-10T13:12:58.402Z',
            amount: 300.0,
            paid: false,
            customer_id: 13,
        },
        {
            id: 21,
            code: 'ORD-021',
            date: '2026-03-10T13:12:58.402Z',
            amount: 450.0,
            paid: false,
            customer_id: 14,
        },
        {
            id: 22,
            code: 'ORD-022',
            date: '2026-03-10T13:12:58.402Z',
            amount: 600.0,
            paid: false,
            customer_id: 15,
        },
        {
            id: 23,
            code: 'ORD-023',
            date: '2026-03-10T13:12:58.402Z',
            amount: 700.0,
            paid: false,
            customer_id: 2,
        },
        {
            id: 24,
            code: 'ORD-024',
            date: '2026-03-10T13:12:58.402Z',
            amount: 100.0,
            paid: false,
            customer_id: 3,
        },
        {
            id: 25,
            code: 'ORD-025',
            date: '2026-03-10T13:12:58.402Z',
            amount: 200.0,
            paid: false,
            customer_id: 5,
        },
        {
            id: 26,
            code: 'ORD-026',
            date: '2026-03-10T13:12:58.402Z',
            amount: 300.0,
            paid: false,
            customer_id: 6,
        },
        {
            id: 27,
            code: 'ORD-027',
            date: '2026-03-10T13:12:58.402Z',
            amount: 400.0,
            paid: false,
            customer_id: 7,
        },
        {
            id: 28,
            code: 'ORD-028',
            date: '2026-03-10T13:12:58.402Z',
            amount: 500.0,
            paid: false,
            customer_id: 8,
        },
        {
            id: 29,
            code: 'ORD-029',
            date: '2026-03-10T13:12:58.402Z',
            amount: 600.0,
            paid: false,
            customer_id: 9,
        },
        {
            id: 30,
            code: 'ORD-030',
            date: '2026-03-10T13:12:58.402Z',
            amount: 700.0,
            paid: false,
            customer_id: 10,
        },

        {
            id: 31,
            code: 'ORD-031',
            date: '2026-03-10T13:12:58.402Z',
            amount: 800.0,
            paid: false,
            customer_id: 11,
        },
        {
            id: 32,
            code: 'ORD-032',
            date: '2026-03-10T13:12:58.402Z',
            amount: 900.0,
            paid: false,
            customer_id: 12,
        },
        {
            id: 33,
            code: 'ORD-033',
            date: '2026-03-10T13:12:58.402Z',
            amount: 1000.0,
            paid: false,
            customer_id: 13,
        },
        {
            id: 34,
            code: 'ORD-034',
            date: '2026-03-10T13:12:58.402Z',
            amount: 110.0,
            paid: false,
            customer_id: 14,
        },
        {
            id: 35,
            code: 'ORD-035',
            date: '2026-03-10T13:12:58.402Z',
            amount: 220.0,
            paid: false,
            customer_id: 15,
        },
        {
            id: 36,
            code: 'ORD-036',
            date: '2026-03-10T13:12:58.402Z',
            amount: 330.0,
            paid: false,
            customer_id: 2,
        },
        {
            id: 37,
            code: 'ORD-037',
            date: '2026-03-10T13:12:58.402Z',
            amount: 440.0,
            paid: false,
            customer_id: 3,
        },
        {
            id: 38,
            code: 'ORD-038',
            date: '2026-03-10T13:12:58.402Z',
            amount: 550.0,
            paid: false,
            customer_id: 5,
        },
        {
            id: 39,
            code: 'ORD-039',
            date: '2026-03-10T13:12:58.402Z',
            amount: 660.0,
            paid: false,
            customer_id: 6,
        },
        {
            id: 40,
            code: 'ORD-040',
            date: '2026-03-10T13:12:58.402Z',
            amount: 770.0,
            paid: false,
            customer_id: 7,
        },

        {
            id: 41,
            code: 'ORD-041',
            date: '2026-03-10T13:12:58.402Z',
            amount: 880.0,
            paid: false,
            customer_id: 8,
        },
        {
            id: 42,
            code: 'ORD-042',
            date: '2026-03-10T13:12:58.402Z',
            amount: 990.0,
            paid: false,
            customer_id: 9,
        },
        {
            id: 43,
            code: 'ORD-043',
            date: '2026-03-10T13:12:58.402Z',
            amount: 150.0,
            paid: false,
            customer_id: 10,
        },
        {
            id: 44,
            code: 'ORD-044',
            date: '2026-03-10T13:12:58.402Z',
            amount: 250.0,
            paid: false,
            customer_id: 11,
        },
        {
            id: 45,
            code: 'ORD-045',
            date: '2026-03-10T13:12:58.402Z',
            amount: 350.0,
            paid: false,
            customer_id: 12,
        },
        {
            id: 46,
            code: 'ORD-046',
            date: '2026-03-10T13:12:58.402Z',
            amount: 450.0,
            paid: false,
            customer_id: 13,
        },
        {
            id: 47,
            code: 'ORD-047',
            date: '2026-03-10T13:12:58.402Z',
            amount: 550.0,
            paid: false,
            customer_id: 14,
        },
        {
            id: 48,
            code: 'ORD-048',
            date: '2026-03-10T13:12:58.402Z',
            amount: 650.0,
            paid: false,
            customer_id: 15,
        },
        {
            id: 49,
            code: 'ORD-049',
            date: '2026-03-10T13:12:58.402Z',
            amount: 750.0,
            paid: false,
            customer_id: 2,
        },
        {
            id: 50,
            code: 'ORD-050',
            date: '2026-03-10T13:12:58.402Z',
            amount: 850.0,
            paid: false,
            customer_id: 3,
        },

        {
            id: 52,
            code: 'ORD-051',
            date: '2026-03-12T14:41:12.682Z',
            amount: 1500.0,
            paid: false,
            customer_id: 1,
        },
        {
            id: 53,
            code: 'ORD-052',
            date: '2026-03-12T14:41:12.682Z',
            amount: 9500.0,
            paid: false,
            customer_id: 2,
        },
        {
            id: 54,
            code: 'ORD-053',
            date: '2026-03-12T14:41:12.682Z',
            amount: 9500.0,
            paid: false,
            customer_id: 7,
        },
        {
            id: 55,
            code: 'ORD-054',
            date: '2026-03-12T14:48:45.539Z',
            amount: 1200.0,
            paid: false,
            customer_id: 1,
        },
        {
            id: 56,
            code: 'ORD-055',
            date: '2026-03-12T14:48:45.539Z',
            amount: 450.0,
            paid: false,
            customer_id: 1,
        },
        {
            id: 57,
            code: 'ORD-056',
            date: '2026-03-12T14:48:45.539Z',
            amount: 300.0,
            paid: false,
            customer_id: 1,
        },

        {
            id: 58,
            code: 'ORD-058',
            date: '2026-03-12T14:50:41.881Z',
            amount: 1200.0,
            paid: false,
            customer_id: 2,
        },
        {
            id: 59,
            code: 'ORD-059',
            date: '2026-03-12T14:50:41.881Z',
            amount: 450.0,
            paid: false,
            customer_id: 2,
        },
        {
            id: 60,
            code: 'ORD-060',
            date: '2026-03-12T14:50:41.881Z',
            amount: 300.0,
            paid: false,
            customer_id: 2,
        },
        {
            id: 61,
            code: 'ORD-061',
            date: '2026-03-12T14:50:41.881Z',
            amount: 150.0,
            paid: false,
            customer_id: 2,
        },
        {
            id: 62,
            code: 'ORD-062',
            date: '2026-03-12T14:50:41.881Z',
            amount: 800.0,
            paid: false,
            customer_id: 2,
        },
    ],
    stores: [
        {
            id: 1,
            title: 'Main Warehouse',
            description: 'Central distribution hub in Kyiv',
        },
        {
            id: 2,
            title: 'Western Hub',
            description: 'Regional warehouse in Lviv',
        },
        {
            id: 3,
            title: 'Southern Port',
            description: 'Import terminal in Odesa',
        },
        {
            id: 4,
            title: 'Eastern Branch',
            description: 'Warehouse facility in Kharkiv',
        },
        {
            id: 5,
            title: 'Retail Outlet',
            description: 'Direct store warehouse in Dnipro',
        },
    ],
};
