GET http://localhost:5000/api/brands

###

GET http://localhost:5000/api/brands/2

###

POST http://localhost:5000/api/brands HTTP/1.1
Content-Type: application/json

{
    "title": "Motorola",
    "description": "Some description about Motorola"
}

###

PUT http://localhost:5000/api/brands HTTP/1.1
Content-Type: application/json

{
    "id": 18,
    "title": "Acer",
    "description": "Some description about Acer"
}

###

DELETE http://localhost:5000/api/brands/18
