# Get all orders (only 10 items)
GET http://localhost:5000/api/orders

###

# Get all orders for IDs greater than half the total
GET http://localhost:5000/api/orders/half

###

# Get orders(array) by customer name
POST http://localhost:5000/api/orders/by-customers HTTP/1.1
Content-Type: application/json

{
    "values": ["Jessica Lee", "Karen White"]
}

###

# Get order by id
GET http://localhost:5000/api/orders/18

###

# Create new order
POST http://localhost:5000/api/orders HTTP/1.1
Content-Type: application/json

{
    "paid": true,
    "customerName": "Ziukov Boris",
    "items": [41, 42, 43, 46, 47]
}

###

# Update existing order by id
PUT http://localhost:5000/api/orders HTTP/1.1
Content-Type: application/json

{
    "id": 53,
    "paid": false,
    "customerName": "Kate Windy",
    "items": [1, 2, 3, 4, 5]
}
###

# Delete order by id
DELETE http://localhost:5000/api/orders/56

###

# Delete orders(array) by customer names
DELETE http://localhost:5000/api/orders/del-by-customers
Content-Type: application/json

{
  "values": ["Ziukov Boris", "Kate Windy"]
}
